libp2p:connect: await storing AgentVersion to metadataBook
libp2p/js-libp2p pull request #1168
Opened 2022-03-11 02:56 UTC by tuyennhv

**Motivation**
+ Lodestar would like to query AgentVersion in "libp2p:connect" event handler

**Description**
+ Await "this.identify()" call when handling "libp2p:connect" event in IdentifyService

2022-03-15 11:23 UTC, achingbrain requested changes

2022-03-15 11:23 UTC, achingbrain commented on src/identify/index.js
> +      await this.identify(connection).catch(log.error)
EventEmitter handlers aren't allow to be async [according to the types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v16/events.d.ts#L330).

2022-03-15 11:25 UTC, achingbrain commented
Could you talk about the use case a bit more?

2022-03-17 10:47 UTC, tuyennhv commented
> Could you talk about the use case a bit more?
> 
> My feeling is there may be a better way - for example usually an application is interested in peers that talk certain protocols, in which case you'd use a topology because when you are notified of a peer joining the topology, identify has completed and their metadata is available in the peer store.

in lodestar, I want to get AgentVersion right after `peer:connect` event. If we can't make event handler async then I'll try other ways at app layer, for example `sleep(0)` or something like that. Thanks for looking into this @achingbrain

2022-03-17 10:47 UTC, closed without merging