Emit peer:connect after all
libp2p/js-libp2p pull request #1171
Opened 2022-03-18 04:37 UTC by tuyennhv

**Motivation**

In lodestar, when we handle "peer:connect" event, we dial the peer which gives another "peer:connect" event and it causes other issues

**Motivation**

In `onConnect` function, "peer:connect" event should be emitted after we add connection to the `connections` map so that when app dial the peer in "peer:connect" event handler, it uses the same/existing connection

2022-03-18 13:36 UTC, wemeetagain approved these changes
LGTM

2022-03-18 13:38 UTC, achingbrain commented
This seems fine to me, and a better way to do it since libp2p should make sure it's internal tracking of connections/addresses/etc is done before informing the outside world a new peer has connected to us.

I'm a little confused though:

> In lodestar, when we handle "peer:connect" event, we dial the peer

`peer:connect` occurs when a peer has connected to us - there's no need to dial them since we already have a connection.

Would you not just open a protocol stream to the peer instead?

That aside, CI appears to be failing due to this change - could you please try running the tests locally and ensure they pass?

2022-03-21 02:20 UTC, tuyennhv commented
> peer:connect occurs when a new connection to a peer has been created, e.g. either when we dial them or when they dial us - there's no need to dial them again in another 'peer:connect' handler since we already have a connection.

> Would you not just open a protocol stream to the peer instead?

what we did is to issue a p2p request in lodestar, which does a `dialProtocol()` behind the scene in libp2p. Since the connection is not added, it'd try to open a new one, all of this logic happen in libp2p

> That aside, CI appears to be failing due to this change - could you please try running the tests locally and ensure they pass?

thanks @achingbrain , this is fixed

2022-04-14 17:07 UTC, achingbrain requested changes
LGTM, just needs some small improvements to the tests

2022-04-14 17:07 UTC, achingbrain commented on test/identify/index.spec.ts
> +      await connectionPromise.promise
Please use `pEvent` instead of `pDefer` here, it's more concise and better reflects the intention behind the code.

2022-04-14 17:07 UTC, achingbrain commented on test/identify/index.spec.ts
> +      await connectionPromise.promise
Please use `pEvent` instead of `pDefer` here, it's more concise and better reflects the intention behind the code.

2022-04-14 17:07 UTC, achingbrain commented on test/upgrading/upgrader.spec.ts
> +    await new Promise<void>((resolve, reject) => {
Please use `pEvent` instead of the hand-rolled promise here, it's more concise and better reflects the intention behind the code.

2022-04-14 17:07 UTC, achingbrain commented on test/dialing/direct.spec.ts
> +    libp2p.connectionManager.addEventListener('peer:connect', () => {
Please use `pEvent` here, it's more concise and better reflects the intention behind the code.

2022-04-20 08:41 UTC, tuyennhv commented
thanks @achingbrain, this `pEvent` is super helpful! Could you help with the failed CI check? It's not related to the fix so I have no ideas.

2022-04-20 17:45 UTC, achingbrain commented
The error message is in the CI output:

```
[08:36:25] dependency-check (production only) [failed]
Command failed with exit code 1: dependency-check package.json src/**/*.js src/**/*.cjs dist/src/**/*.js utils/**/*.js utils/**/*.cjs --missing --no-dev -i @types/* -i @types/* --extensions cjs:detective-cjs --extensions js:detective-es6
Fail! Dependencies not listed in package.json: @libp2p/tracked-map, it-pair
```

Basically `aegir` has got better at spotting unused/missing deps.  `@libp2p/tracked-map` and `it-pair` are production deps that are erroneously declared as development deps, they just need moving from the `"devDependencies"` block to the the "dependencies" block in the project's `package.json` file.

2022-04-22 19:55 UTC, achingbrain approved these changes

2022-04-22 19:56 UTC, achingbrain commented
The fix for the final failing build job was merged as part of #1194 - this is good to go.

2022-04-22 19:56 UTC, merged