Updating instructions in examples/transports tut
libp2p/js-libp2p pull request #1200
Opened 2022-04-28 13:09 UTC by walkerlj0

Updated part 1  (1.js)

2022-05-03 15:50 UTC, BigLep commented
2022-05-03 conversation: there are two things in this PR: 
1. moving back to CJS
2. some new/helpful content

We don't want the move back to CJS given we are making js-libp2p ESM-only.  We do want the new/helpful content.

@walkerlj0 : if you are wanting to contribute more here, please reduce to #2 only.  Otherwise, it will get picked up once the EMS-only js-libp2p is released.

2022-05-16 19:14 UTC, wemeetagain commented
@walkerlj0 libp2p 0.37.0 has finally been released with ESM-only exports.

Can you try to make the examples run against the latest version?

2022-05-24 15:39 UTC, wemeetagain requested changes

2022-05-24 15:39 UTC, wemeetagain commented on examples/transports/README.md
> +})
Can you revert the changes other than this? We want to keep examples using the latest versions of libp2p dependencies, using ESM imports, etc.

2022-06-07 15:57 UTC, BigLep commented
@walkerlj0: are you able to incorporate the feedback so the PR can be merged?

2022-06-07 20:33 UTC, walkerlj0 commented
I will try and run it in the next coupld days, so sorry, been swamped!

2022-06-21 15:32 UTC, mpetrunic commented
@walkerlj0 we converted it to draft state until you are ready.

2022-06-21 23:34 UTC, walkerlj0 commented
@mpetrunic tried running transports/1.js and got this error, advice on how to troubleshoot?

`file:///Users/lindsayjowalker/Git/js-libp2p/examples/transports/1.js:3
const Libp2p = require('libp2p')
               ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/lindsayjowalker/Git/js-libp2p/examples/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/lindsayjowalker/Git/js-libp2p/examples/transports/1.js:3:16
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)`

2022-06-23 11:44 UTC, mpetrunic commented
> @mpetrunic tried running transports/1.js and got this error, advice on how to troubleshoot?
> 
> **Note I did fetch upstream from libp2p:master
> 
> ```
> file:///Users/lindsayjowalker/Git/js-libp2p/examples/transports/1.js:3
> const Libp2p = require('libp2p')
>                ^
> 
> ReferenceError: require is not defined in ES module scope, you can use import instead
> This file is being treated as an ES module because it has a '.js' file extension and '/Users/lindsayjowalker/Git/js-libp2p/examples/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
>     at file:///Users/lindsayjowalker/Git/js-libp2p/examples/transports/1.js:3:16
>     at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
>     at async loadESM (node:internal/process/esm_loader:88:5)
>     at async handleMainPromise (node:internal/modules/run_main:65:12)
> ```

If you fetched latest master, do `npm install` in root followed by `npm run build`. Also do `npm install` in the examples directory. You shouldn't have `require` statement anywhere, if you have you probably have some local changes or you didn't pull latest libp2p:master.

Gonna close this PR as examples work just fine for me locally!

2022-06-23 11:44 UTC, closed without merging