fix: do not override known address after identify is done
libp2p/js-libp2p pull request #1485
Opened 2022-11-21 05:59 UTC by fryorcraken

Identify protocol being executed it means that both peers are somehow connected. Hence, it should not override working multiaddresses but only add to it.

2022-11-21 05:59 UTC, fryorcraken commented
Another fix would be to not add the addresses at all to the address book.

2022-11-25 15:31 UTC, achingbrain commented
If we don't evict old addresses, there's a risk the list of known addresses for a remote peer will grow and grow, eventually growing beyond the [maxDialsPerPeer](https://github.com/libp2p/js-libp2p/blob/master/src/config.ts#L28) limit which will cause dials to fail in a hard to debug way.

The question really is, why is the remote peer sending you `0.0.0.0` addresses?

2022-11-25 15:31 UTC, achingbrain requested changes
If we don't evict old addresses, there's a risk the list of known addresses for a remote peer will grow and grow, eventually growing beyond the [maxDialsPerPeer](https://github.com/libp2p/js-libp2p/blob/master/src/config.ts#L28) limit which will cause dials to fail in a hard to debug way.

The question really is, why is the remote peer sending you `0.0.0.0` addresses?

2022-11-28 11:52 UTC, fryorcraken commented
Continuing discussion at https://github.com/libp2p/js-libp2p/issues/1484#issuecomment-1328946339

2022-11-28 11:52 UTC, closed without merging