fix: compare unsanitized number using gte
libp2p/js-libp2p pull request #1570
Opened 2023-01-28 11:01 UTC by wemeetagain

If maxConnections is passed in as a float, this will result in disconnecting all peers due to this strict equality check.

This may happen unintentionally if maxConnections is set dynamically.

This is a patch to avoid this unfortunate failure mode.

Likely more thought should go into a systematic approach to handling these situations.

2023-01-28 20:20 UTC, maschad commented
I can't conceptualize a fraction of a connection so I would suggest we convert any value set as a  ‘maxConnection‘ to a positive integer value internally - using something like [Math.trunc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc) - before we perform operations with that value. What do you think?

2023-01-28 20:21 UTC, maschad requested changes
I can't conceptualize a fraction of a connection so I would suggest we convert any value set as a `maxConnections` to a positive integer value internally - using something like [Math.trunc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc) - before we perform operations with that value.

2023-01-30 03:19 UTC, maschad commented
I opened up https://github.com/libp2p/js-libp2p/pull/1572 in favour of this solution

2023-01-30 23:53 UTC, wemeetagain commented
Yea opened this PR mainly for discussion.

I think ideally we can/should validate user options in some more systematic way. Not sure about coersing user values, that could cause some confusion. Perhaps better to just throw when they are invalid.

2023-01-31 01:55 UTC, maschad commented
> I think ideally we can/should validate user options in some more systematic way. Not sure about coersing user values, that could cause some confusion. Perhaps better to just throw when they are invalid.

Agreed. That was also [the suggestion made here](https://github.com/libp2p/js-libp2p/pull/1572#pullrequestreview-1274842562)

2023-02-14 16:53 UTC, achingbrain commented
Closing as we are going to implement more comprehensive config validation - https://github.com/libp2p/js-libp2p/issues/1573

2023-02-14 16:53 UTC, closed without merging