fix(content-routing:utils): improve requirePeers error msg
libp2p/js-libp2p pull request #1647
Opened 2023-03-23 19:53 UTC by SgtPooki

This error message of "not found" is completely unhelpful when developing. I imagine providing more context would save devs some time

2023-03-24 15:25 UTC, maschad requested changes
Thanks for this @SgtPooki ! I do wonder if `NOT_FOUND` is more appropriate than `ERROR` as peers have been found, but they are below the threshold.

2023-03-24 15:25 UTC, maschad commented on src/content-routing/utils.ts
> +    throw new CodeError(`requirePeers failed with ${seen} of ${min} required peers.`, 'NOT_FOUND')
```suggestion
 throw new CodeError(`more peers required, seen:${seen}  min: ${min} .`, 'NOT_FOUND')
 ````

2023-04-03 13:33 UTC, achingbrain approved these changes

2023-04-03 14:44 UTC, maschad approved these changes

2023-04-03 14:45 UTC, merged