fix: use peer events in registrar
libp2p/js-libp2p pull request #1773
Opened 2023-05-25 13:07 UTC by achingbrain

Refactors the registrar to use `peer:connect` and `peer:disconnect` events instead of `connection:open` and `connection:close`.

The connection events are too low-level for the purpose and can cause a race condition when multiple multiaddrs are dialed at the same time.

When this happens the first connection survives and others are closed but their corresponding `connection:open` event has already fired.

Interested parties registering topologies have their onConnect event invoked with the soon-to-be-closed connection.

The `peer:connect` event happens later in the lifecycle by which point the extra connection has been closed.

2023-05-25 13:37 UTC, maschad requested changes
Looks good, just one comment

2023-05-25 13:51 UTC, maschad approved these changes

2023-05-25 13:52 UTC, merged

2023-05-25 15:31 UTC, marcus-pousette commented
So this will essentially solve/fix https://github.com/libp2p/js-libp2p/issues/1755 ? I wrote this issue because I had problems when doing multi-dialing.

Is this a breaking change also? Will protocol handlers work differently as only one connection event will be emitted in the toplogies?

2023-05-25 15:39 UTC, achingbrain commented
Yes, I think it should solve #1755.

It's not a breaking change because the topology is intended to be notified when a peer that supports the given protocol connects/disconnects, not when they open a connection.

The `connection:open` event is the wrong time to do it anyway since identify hasn't run yet (which is how we discover which protocols a peer supports) - the topology is only notified in this case when a peer has reconnected.

Notifying topologies mostly happens after the `peer:update` event which happens when `libp2p.peerStore.merge` or `libp2p.peerStore.update` is called in a way that updates the peer's protocol list, for example after the first identify.

2023-05-26 09:56 UTC, marcus-pousette commented
Aha ok! Thanks for the info