test: run tests on webkit for webRTC
libp2p/js-libp2p pull request #1832
Opened 2023-06-16 16:18 UTC by maschad

2023-06-26 10:04 UTC, achingbrain requested changes

2023-06-26 10:04 UTC, achingbrain commented on packages/transport-webrtc/package.json
> +    "dep-check": "aegir dep-check -i protons"
This is already in the [default ignore list](https://github.com/ipfs/aegir/blob/369453f7543488d43e72721c48320d6d8d59b705/src/dependency-check.js#L13)

```suggestion
    "dep-check": "aegir dep-check"
```

2023-06-26 10:04 UTC, achingbrain commented on packages/transport-webrtc/package.json
> +    "libp2p": "^0.45.9",
Not necessary as this is a monorepo sibling and this change will be undone by `aegir check-project`.

```suggestion
    "libp2p": "^0.45.0",
```

2023-06-26 10:04 UTC, achingbrain commented on packages/transport-webrtc/package.json
> +    "@libp2p/websockets": "^6.0.3",
Not necessary as these are monorepo siblings and this change will be undone by `aegir check-project`.

```suggestion
    "@libp2p/peer-id-factory": "^2.0.0",
    "@libp2p/websockets": "^6.0.0",
```

2023-06-26 10:04 UTC, achingbrain commented on packages/transport-webrtc/test/basics.spec.ts
> +  // TODO: Streams are not closing gracefully, re-introduce after https://github.com/libp2p/js-libp2p/issues/1793 is addressed
The issue in #1793 does not prevent nodes from stopping.  It prevents stream data from being sent to the remote before the stream is closed.

Why does that mean these lines need to be commented out?

2023-07-04 07:33 UTC, achingbrain requested changes
This needs a `test:webkit` script added to the `package.json` in the monorepo root as well, otherwise the webkit tests will not be run.

2023-07-04 20:47 UTC, maschad commented
it seems on webkit that the `RTCDataChannel` doesn't send the `arraybuffer` binaryType the same way that other browsers do, which results [in some failures when closing a connection](https://github.com/libp2p/js-libp2p/actions/runs/5455886352/jobs/9928054478?pr=1832#step:6:562), I a bit unsure how to proceed as the only way I have gotten this to [work is to add a` delay(10)` or greater](https://github.com/libp2p/js-libp2p/pull/1832/files#diff-05b91eb525d98768ddd0ab5a8d129630baf7b747a59df7ce6418fefb9c3c4f22R158), which is obviously not a fix.

2023-08-30 22:31 UTC, maschad commented
Currently blocked per https://github.com/libp2p/js-libp2p-webrtc/pull/177#issuecomment-1589529908

2023-08-30 22:39 UTC, maschad commented
Closing this until https://github.com/libp2p/js-libp2p/issues/2007 is resolved

2023-08-30 22:39 UTC, closed without merging