chore: re-enable doc-check
libp2p/js-libp2p pull request #2250
Opened 2023-11-21 03:05 UTC by maschad

## Title

## Description

## Notes & open questions

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-11-21 03:07 UTC, maschad commented on doc/package.json
> +  "exports": {},
This is a hack for now given that [typescript docs verifier](https://github.com/bbc/typescript-docs-verifier/blob/30a2d634b7cae88b68d8cbcbcb873b222ea3b732/src/PackageInfo.ts#L69) relies on the exports for its check

2023-11-21 14:43 UTC, achingbrain commented on doc/METRICS.md
> +  logger: defaultLogger()
I understand why this is necessary but I don't think makes for the clearest documentation.  Perhaps these examples can be refactored to be a generic libp2p service that receives a `Metrics` object and adds  metrics to it?

Then we wouldn't need to get loggers involved.

2023-11-28 11:44 UTC, achingbrain requested changes
There are some good doc improvements in here so I'd like to merge this but where is the bit of the PR that re-enables doc-check for TypeScript snippets like the title says?

2023-11-28 17:56 UTC, maschad commented
Strange, I had assumed [CI was running the command](https://github.com/libp2p/js-libp2p/actions/runs/7018198824/job/19093168666?pr=2250) and that the actual `doc-check` command was a no-op, which is what this PR addressed. Turns out the CI was also a no-op as well, so I pushed a commit to fix in de72f20.

It also turns out [a recent typescript upgrade](https://github.com/microsoft/TypeScript/issues/56508) broke [ts-node](https://github.com/TypeStrong/ts-node/issues/2076#issuecomment-1823221840) which `typescript-docs-verifier` depends on so I am using a fixed Typescript version until that gets resolved and the ts-node fix should bubble upstream.

2023-12-15 11:21 UTC, achingbrain commented on doc/package.json
> +    "typescript": "5.2.2"
Let's wait for the fix to bubble up instead of trying to manage multiple versions of typescript in the monorepo.

2024-01-11 20:37 UTC, wemeetagain approved these changes

2024-01-31 14:56 UTC, achingbrain approved these changes

2024-01-31 14:56 UTC, merged