feat: add local definition of isPrivateIp
libp2p/js-libp2p pull request #2362
Opened 2024-01-16 17:42 UTC by wemeetagain

## Description

Use local defintion of isPrivateIp instead of `private-ip` package
This should reduce bundle size and remove another commonjs sub-dependency (`ipaddr.js`)

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

2024-01-16 18:27 UTC, maschad requested changes
You should verify  that this decreases the [bundle size](https://github.com/libp2p/js-libp2p/blob/cce373ff82a959ba4cacc74a8d980109264c1705/packages/kad-dht/.aegir.js#L5C27-L5C27) and update the limits as well for each package so that this change is worthwhile.

2024-01-17 21:42 UTC, wemeetagain commented on packages/utils/test/private-ip.spec.ts
> +/* eslint-env mocha */
yes, also the source is a modified version of https://github.com/frenchbread/private-ip/blob/master/src/index.ts

2024-01-17 21:45 UTC, wemeetagain commented
> You should verify that this decreases the bundle size

Its guaranteed to be smaller because its the same code, but with two fewer dependencies.

2024-01-18 17:57 UTC, wemeetagain commented
@achingbrain ready for re-review

2024-01-18 18:25 UTC, merged