support custom listener options
libp2p/js-libp2p pull request #822
Opened 2020-12-04 08:43 UTC by lovemyliwu

2020-12-04 09:16 UTC, vasco-santos requested changes
Thanks for this PR @lovemyliwu 
Can you update https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#customizing-transports to document how to configure the listener and add a test?

2020-12-04 09:37 UTC, lovemyliwu commented
Sure, but maybe do it later next week

2020-12-04 09:38 UTC, vasco-santos commented
> Sure, but maybe do it later next week

Thanks, that is fine! Just @mention me once I can have a look

2020-12-07 06:51 UTC, lovemyliwu commented
@vasco-santos please review

2020-12-07 09:47 UTC, vasco-santos requested changes
Overall this looks good! thanks, just need some improvements on the docs

2020-12-07 09:47 UTC, vasco-santos commented on doc/CONFIGURATION.md
> +Libp2p will auto call `createListener` after initialized transport, if you want custom listener options, you can provide `listenerOptions` in your transport option. For example, `libp2p-webrtc-star`
```suggestion
During Libp2p startup, transport listeners will be created for the configured listen multiaddrs.  Some transports support custom listener options and you can set them using the `listenerOptions` in the transport configuration. For example, [libp2p-webrtc-star](https://github.com/libp2p/js-libp2p-webrtc-star) transport listener supports the configuration of its underlying [simple-peer](https://github.com/feross/simple-peer) ice server(STUN/TURN) config as follows:
```

2020-12-07 09:47 UTC, vasco-santos commented on doc/CONFIGURATION.md
> +  },
```suggestion
  },
  addresses: {
    listen: ['/dns4/your-wrtc-star.pub/tcp/443/wss/p2p-webrtc-star'] // your webrtc dns multiaddr
  }
```

2020-12-07 09:47 UTC, vasco-santos commented on doc/CONFIGURATION.md
> +  },
We need to specify a listen address so that the transport listener is created

2020-12-08 01:56 UTC, lovemyliwu commented
@vasco-santos please review again

2020-12-08 10:06 UTC, vasco-santos approved these changes
LGTM!
THanks @lovemyliwu

2020-12-09 15:30 UTC, jacobheun approved these changes

2020-12-09 15:31 UTC, merged