Update CONFIGURATION.md
libp2p/js-libp2p pull request #982
Opened 2021-08-27 22:09 UTC by Leask

https://github.com/ipfs/js-datastore-level/issues/85

2021-08-28 15:30 UTC, vasco-santos requested changes
Thanks for the PR @Leask 

The `interface-datastore` does not seem to mention that `.open()` will return the datastore. While this might be true today in some (or all) implementations of the interface, it can change in the future. So, can we change the added code in the docs to call open in a new line after creating the datastore?

2021-08-28 23:52 UTC, Leask commented
@vasco-santos updated as your request.

2021-08-30 10:00 UTC, vasco-santos requested changes

2021-08-30 10:00 UTC, vasco-santos commented on doc/CONFIGURATION.md
> +const dsInstant = await datastore.open()
```suggestion
await datastore.open()
```

2021-08-30 10:00 UTC, vasco-santos commented on doc/CONFIGURATION.md
> +    datastore: dsInstant,
```suggestion
    datastore,
```

2021-08-30 10:00 UTC, vasco-santos commented on doc/CONFIGURATION.md
> +const dsInstant = await datastore.open()
```suggestion
await datastore.open()
```

2021-08-30 10:00 UTC, vasco-santos commented on doc/CONFIGURATION.md
> +  datastore: dsInstant,
```suggestion
  datastore,
```

2021-08-30 10:01 UTC, vasco-santos commented on doc/CONFIGURATION.md
> +const dsInstant = await datastore.open()
sorry if I was not clear enough, but I was meaning this way

2021-08-31 05:02 UTC, Leask commented
I accepted all changes.

2021-08-31 09:51 UTC, vasco-santos approved these changes
Thanks @Leask

2021-08-31 09:51 UTC, merged